[[language]]
name = "go"
file-types = ["go", "go.mod", "go.sum"]
roots = ["go.mod", ".git"]
language-servers = ["gopls"]

[[language]]
name = "typescript"
file-types = ["ts", "mts", "cts"]
roots = ["package.json", "tsconfig.json"]
language-servers = ["tsgo"]

[[language]]
name = "typescriptreact"
file-types = ["tsx"]
roots = ["package.json", "tsconfig.json"]
language-servers = ["tsgo"]

[[language]]
name = "javascript"
file-types = ["js", "mjs", "cjs"]
roots = ["package.json", "tsconfig.json"]
language-servers = ["tsgo"]

[[language]]
name = "javascriptreact"
file-types = ["jsx"]
roots = ["package.json", "tsconfig.json"]
language-servers = ["tsgo"]

[[language]]
name = "vue"
file-types = ["vue"]
roots = ["package.json", "tsconfig.json"]
language-servers = ["vue-language-server"]

[[language]]
name = "toml"
file-types = ["toml"]
roots = []

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
roots = []

[[language]]
name = "json"
file-types = ["json", "jsonc"]
roots = []

[[language]]
name = "markdown"
file-types = ["md", "markdown", "mdx"]
roots = ["package.json", "tsconfig.json"]
language-servers = ["tsgo"]

[[language]]
name = "bash"
file-types = ["sh", "bash", "zsh", ".bashrc", ".zshrc", ".bash_profile", ".zprofile", ".profile"]
roots = []

[[language]]
name = "gitignore"
file-types = [".gitignore", ".dockerignore"]
roots = []

[[language]]
name = "makefile"
file-types = ["Makefile", "makefile", "GNUmakefile", "mk"]
roots = []

[language-server.gopls]
command = "gopls"
args = []

[language-server.tsgo]
command = "tsgo"
args = ["--lsp", "-stdio"]

[language-server.vue-language-server]
command = "vue-language-server"
args = ["--stdio"]

[language-server.vue-language-server.initialization-options.typescript]
tsdk = "/Users/diver/.nvm/versions/node/v24.13.0/lib/node_modules/@vue/language-server/node_modules/typescript/lib"
